# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('repository', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Moduletype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('server', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tasktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='repositoryserver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci.Repository'),
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci.Moduletype'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ci.Tasktype'),
            preserve_default=False,
        ),
    ]
