# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0003_auto_20170918_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='value',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
