# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0004_auto_20170918_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='task',
            field=models.ManyToManyField(to='ci.Task', verbose_name='task list'),
        ),
    ]
