# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0005_feature_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='module',
            field=models.ManyToManyField(to='ci.Module', verbose_name='subsystem list'),
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ci.Featuretype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuretype',
            name='priority',
            field=models.IntegerField(default=10),
        ),
    ]
