# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0006_auto_20170918_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ci.Product'),
            preserve_default=False,
        ),
    ]
