# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0007_feature_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caseset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Casetags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='devcaseset',
            field=models.ManyToManyField(to='ci.Caseset', verbose_name='case set for develop'),
        ),
        migrations.AddField(
            model_name='feature',
            name='devtags',
            field=models.ManyToManyField(to='ci.Casetags', verbose_name='case tag for develop'),
        ),
    ]
