# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0008_auto_20170918_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='relcaseset',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feature',
            name='reltags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feature',
            name='tempcaseset',
            field=models.ManyToManyField(to='ci.Caseset', verbose_name='case set for develop'),
        ),
        migrations.AddField(
            model_name='feature',
            name='temptags',
            field=models.ManyToManyField(to='ci.Casetags', verbose_name='case tag for develop'),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='devcaseset',
        ),
        migrations.AddField(
            model_name='feature',
            name='devcaseset',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='devtags',
        ),
        migrations.AddField(
            model_name='feature',
            name='devtags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
