# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0009_auto_20170918_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='repository',
            field=models.CharField(default='', max_length=200),
        ),
    ]
