# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0012_auto_20170919_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcaseset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('caseset', models.ManyToManyField(to='ci.Caseset', verbose_name='test case set')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='devcaseset',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='devtags',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='relcaseset',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='reltags',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='tempcaseset',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='temptags',
        ),
    ]
