# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0013_auto_20170919_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relcaseset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('caseset', models.ManyToManyField(to='ci.Caseset', verbose_name='test case set')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci.Product')),
            ],
        ),
        migrations.RenameModel(
            old_name='Testcaseset',
            new_name='Devcaseset',
        ),
        migrations.AddField(
            model_name='feature',
            name='devtags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feature',
            name='relcaseset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Devcaseset'),
        ),
        migrations.AddField(
            model_name='feature',
            name='reltags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feature',
            name='devcaseset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Relcaseset'),
        ),
    ]
