# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0015_auto_20170919_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='params',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='envvariable',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Product'),
        ),
        migrations.AddField(
            model_name='envvariable',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Task'),
        ),
    ]
