# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0017_featurebuilder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envvariable',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Task'),
        ),
    ]
