# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0018_auto_20170919_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envvariable',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Product'),
        ),
    ]
