# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0019_auto_20170919_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='branch',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feature',
            name='featureid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
