# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0020_auto_20170919_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devcasetags',
            old_name='caseset',
            new_name='tagset',
        ),
        migrations.RenameField(
            model_name='relcasetags',
            old_name='caseset',
            new_name='tagset',
        ),
    ]
