# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0021_auto_20170919_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='params',
            field=models.TextField(blank='', default=''),
        ),
    ]
