# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0022_task_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='devcaseset',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='devtags',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='relcaseset',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='reltags',
        ),
        migrations.AddField(
            model_name='feature',
            name='params',
            field=models.TextField(blank=True, default='', help_text='used to redefine task paramers'),
        ),
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.TextField(blank=True, default='', help_text="use to define the task params. one line is one key-value!\n\n       var name start with '__' will be reload in feature\n       example: key1=value1\n                key2=value2\n                key3=\n                key4=\n                __key5=value5\n    "),
        ),
    ]
