# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0023_auto_20170920_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devcaseset',
            new_name='Userdefcaseset',
        ),
        migrations.RenameModel(
            old_name='Devcasetags',
            new_name='Userdeftagset',
        ),
        migrations.RemoveField(
            model_name='relcaseset',
            name='caseset',
        ),
        migrations.RemoveField(
            model_name='relcaseset',
            name='product',
        ),
        migrations.RemoveField(
            model_name='relcasetags',
            name='product',
        ),
        migrations.RemoveField(
            model_name='relcasetags',
            name='tagset',
        ),
        migrations.DeleteModel(
            name='Relcaseset',
        ),
        migrations.DeleteModel(
            name='Relcasetags',
        ),
    ]
