# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0024_auto_20170920_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casetags',
            new_name='Casetag',
        ),
    ]
