# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0025_auto_20170920_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends',
            field=models.ManyToManyField(related_name='_task_depends_+', to='ci.Task'),
        ),
    ]
