# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0029_build_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Gearman'),
        ),
        migrations.AlterField(
            model_name='build',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Task'),
        ),
    ]
