# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0030_auto_20170921_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='buildurl',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='build',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Feature'),
        ),
        migrations.AlterField(
            model_name='build',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='build',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Status'),
        ),
        migrations.AlterField(
            model_name='build',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
