# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0031_auto_20170921_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearman',
            name='value',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
