# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0032_gearman_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurebuilder',
            name='builds',
        ),
        migrations.AddField(
            model_name='featurebuilder',
            name='uuid',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
