# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0034_build_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gearman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ci.Gearman'),
            preserve_default=False,
        ),
    ]
