# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0035_task_gearman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='uuid',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
