# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0036_auto_20170925_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Featurebuilder'),
        ),
    ]
