# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0037_auto_20170925_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('table', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caseset',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseset',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='casetag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetag',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='envvariable',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envvariable',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='featurebuilder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurebuilder',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='featuretype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuretype',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gearman',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gearman',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduletype',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='status',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktype',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdefcaseset',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdefcaseset',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdeftagset',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdeftagset',
            name='lastupdate_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
