# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0038_auto_20171009_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=500)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci.Task')),
            ],
        ),
        migrations.AddField(
            model_name='key_tables',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ci.Task'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='feature',
            name='params',
        ),
        migrations.AddField(
            model_name='feature',
            name='params',
            field=models.ManyToManyField(to='ci.Param', verbose_name='subsystem list'),
        ),
    ]
