# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0040_auto_20171011_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskParam',
        ),
    ]
